In [1]:
# Import the numpy package under the name np
import numpy as np

In [2]:
# Print the numpy version and the configuration
print(np.__version__)

1.18.1


In [3]:
# Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# How to find the memory size of any array
print(x.size)

10


In [5]:
# How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
# Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# Create a vector with values ranging from 10 to 49
z = np.arange(10, 49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
# Reverse a vector (first element becomes last) 
rz = z[::-1]
print(rz)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
b = np.array([1,2,0,0,4,0])
print(b)

c = np.nonzero(b)
print("Indices of non-zero elements: ", c)

[1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [11]:
# Create a 3x3 identity matrix
d = np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Create a 3x3x3 array with random values
e = np.random.random((3, 3, 3))
print(e)

[[[0.53274053 0.65682099 0.8814404 ]
  [0.12640952 0.66718919 0.39524063]
  [0.4566219  0.1050557  0.31748398]]

 [[0.54225999 0.01420708 0.91569701]
  [0.54517482 0.02156472 0.3716288 ]
  [0.95931497 0.63479432 0.18201271]]

 [[0.10964886 0.49626787 0.79932316]
  [0.66403371 0.37577487 0.80971476]
  [0.32987764 0.19197943 0.03178128]]]


In [13]:
# Create a 10x10 array with random values and find the minimum and maximum values
f = np.random.random((10, 10))
print(f)
fmin = f.min()
fmax = f.max()
print(fmin, fmax)

[[0.68632615 0.44259702 0.92246112 0.80949475 0.79555482 0.14268607
  0.42521095 0.70800956 0.44413341 0.88586744]
 [0.33557477 0.56587534 0.37852055 0.76191143 0.41533409 0.12166528
  0.93199158 0.50564208 0.73643577 0.01783505]
 [0.19398676 0.84311131 0.39178666 0.19530153 0.15993326 0.94015408
  0.4355555  0.87156481 0.81906007 0.6811025 ]
 [0.30693639 0.99230239 0.56994857 0.12675847 0.37423115 0.3820581
  0.83687829 0.90579737 0.92834402 0.0372873 ]
 [0.94017341 0.62275019 0.18843497 0.91849684 0.62882363 0.34843948
  0.01952219 0.30470504 0.23186549 0.32271792]
 [0.97203248 0.43159462 0.21753762 0.99681829 0.11428902 0.73820663
  0.73487721 0.51131602 0.65848199 0.39829648]
 [0.8767285  0.5064575  0.82205092 0.71351159 0.55413498 0.44506062
  0.99311378 0.16342348 0.12682824 0.33398349]
 [0.06113033 0.67978631 0.74193348 0.92120288 0.53150256 0.85289797
  0.80030297 0.51983334 0.72401349 0.08791856]
 [0.40574728 0.38567403 0.26163033 0.59336212 0.38333928 0.81654723
  0.15484739 

In [14]:
# Create a random vector of size 30 and find the mean value
g = np.random.random(30)
print(g)
gmean = g.mean()
print(gmean)

[0.719034   0.05123467 0.00888793 0.05735156 0.5201871  0.39469576
 0.42748949 0.24569216 0.74859151 0.04840089 0.55594544 0.72678298
 0.3106406  0.0817684  0.75021731 0.48743968 0.81183605 0.00280313
 0.41426819 0.98527033 0.7252863  0.80018661 0.89564117 0.41881134
 0.63816686 0.44323543 0.1204533  0.67874559 0.84406611 0.56427894]
0.48258029382547135


In [15]:
# Create a 2d array with 1 on the border and 0 inside
h = np.ones((5,5))
h[1:-1, 1:-1] = 0
print(h)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# How to add a border (filled with 0's) around an existing array
i = np.random.permutation(25).reshape(5,5)
print("Original array: ")
print(i)

Original array: 
[[18 22 15  0 16]
 [12  5  6 14  7]
 [ 1  2 24 21 19]
 [ 4 23 20 17 11]
 [10 13  8  3  9]]


In [17]:
inew = np.pad(i, pad_width = 1, mode = 'constant', constant_values = 0)
print(inew)

[[ 0  0  0  0  0  0  0]
 [ 0 18 22 15  0 16  0]
 [ 0 12  5  6 14  7  0]
 [ 0  1  2 24 21 19  0]
 [ 0  4 23 20 17 11  0]
 [ 0 10 13  8  3  9  0]
 [ 0  0  0  0  0  0  0]]


In [18]:
# What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
j = np.diag(1+np.arange(4), k = -1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
k = np.zeros((8,8), dtype = int)
k[1::2, ::2] = 1
k[::2, 1::2] = 1
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [22]:
# Create a checkerboard 8x8 matrix using the tile function
l = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))
print(l)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [23]:
# Normalize a 5x5 random matrix
m = np.random.random((5, 5))
mnorm = (m - np.mean(m)) / (np.std(m))
print(mnorm)

[[ 1.62361518  1.55497611 -0.84541503  0.5771963   0.50549839]
 [-1.57536783  0.12608873  0.47331698 -0.11220866  0.67692703]
 [ 0.92337621 -1.17235406  0.93898749  1.01214444 -1.10490431]
 [-0.23986812 -0.6607989  -1.23072056 -1.15129102  0.59230227]
 [ 1.14820355 -1.1669196  -0.46718582 -1.52083886  1.09524011]]


In [24]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [25]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
o = np.arange(15)
print(o)

o[(3 < o) & (o < 8)] *= -1
print(o)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


In [27]:
# What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [32]:
# Consider an integer vector Z, which of these expressions are legal?
o = np.arange(15)
o**o
2 << o >> 2
o <- o
1j*o
o/1/1
# o<o>o    Only this is invalid

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [33]:
# What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-2.14748365e+09])

In [34]:
# How to round away from zero a float array ?
p = np.random.uniform(-10, +10, 10)
pnew = np.copysign(np.ceil(np.abs(p)), p)
print(pnew)

[-9. -3. -8. -6. -4.  4.  2.  3.  6.  6.]


In [35]:
# How to find common values between two arrays?
q1 = np.random.randint(0, 10, 10)
q2 = np.random.randint(0, 10, 10)
common = np.intersect1d(q1, q2)
print(common)

[1 2 4 5]


In [36]:
# How to ignore all numpy warnings (not recommended)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [37]:
# Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [40]:
# How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday", yesterday)
print("Today", today)
print("Tomorrow", tomorrow)

Yesterday 2021-07-05
Today 2021-07-06
Tomorrow 2021-07-07


In [41]:
# How to get all the dates corresponding to the month of July 2016
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [42]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [43]:
#  Extract the integer part of a random array of positive numbers using 4 different methods
r = np.random.uniform(0, 10, 10)

print(r - r%1)
print(r // 1)
print(np.floor(r))
print(r.astype(int))
print(np.trunc(r))

[5. 9. 8. 7. 4. 2. 4. 2. 0. 6.]
[5. 9. 8. 7. 4. 2. 4. 2. 0. 6.]
[5. 9. 8. 7. 4. 2. 4. 2. 0. 6.]
[5 9 8 7 4 2 4 2 0 6]
[5. 9. 8. 7. 4. 2. 4. 2. 0. 6.]
