In [1]:
# Import the numpy package under the name np
import numpy as np

In [2]:
# Print the numpy version and the configuration
print(np.__version__)

1.18.1


In [3]:
# Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# How to find the memory size of any array
print(x.size)

10


In [5]:
# How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
# Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# Create a vector with values ranging from 10 to 49
z = np.arange(10, 49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
# Reverse a vector (first element becomes last) 
rz = z[::-1]
print(rz)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
b = np.array([1,2,0,0,4,0])
print(b)

c = np.nonzero(b)
print("Indices of non-zero elements: ", c)

[1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [11]:
# Create a 3x3 identity matrix
d = np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Create a 3x3x3 array with random values
e = np.random.random((3, 3, 3))
print(e)

[[[0.82673514 0.30065743 0.01093033]
  [0.79722947 0.37117773 0.29885833]
  [0.76311573 0.99136708 0.08487283]]

 [[0.99662814 0.00596676 0.90667824]
  [0.98482289 0.73053911 0.09176193]
  [0.69459434 0.83934443 0.74863939]]

 [[0.56302423 0.08483149 0.94691706]
  [0.54776566 0.1497711  0.70870876]
  [0.35211383 0.13537885 0.00561395]]]


In [13]:
# Create a 10x10 array with random values and find the minimum and maximum values
f = np.random.random((10, 10))
print(f)
fmin = f.min()
fmax = f.max()
print(fmin, fmax)

[[0.53921955 0.27105643 0.29619223 0.13262026 0.02999488 0.09803707
  0.85805325 0.08674637 0.96722478 0.1328925 ]
 [0.9903321  0.3563619  0.88928794 0.24508389 0.26446488 0.12664413
  0.04170553 0.36578269 0.86278363 0.06059917]
 [0.59884906 0.11556952 0.17080098 0.83727469 0.90202299 0.33191521
  0.73245667 0.96523418 0.79470781 0.53766186]
 [0.40869156 0.28215392 0.35375129 0.33398636 0.07140452 0.76668227
  0.15767215 0.68433841 0.40385247 0.61890813]
 [0.16441014 0.92344261 0.28681931 0.3329531  0.89082816 0.05006414
  0.76425472 0.16393571 0.3941741  0.04578391]
 [0.14905501 0.91353298 0.92223538 0.64697855 0.61895066 0.30224283
  0.96659612 0.53629268 0.12664584 0.55055663]
 [0.27456474 0.87675821 0.7444455  0.36534878 0.28142313 0.3461466
  0.21340305 0.31590922 0.54108067 0.05906786]
 [0.25609298 0.77497823 0.61681981 0.71127511 0.97102701 0.58933874
  0.96610845 0.38813919 0.1886322  0.7168022 ]
 [0.80580601 0.34027661 0.00551238 0.75478985 0.01466152 0.12808051
  0.50775516 

In [14]:
# Create a random vector of size 30 and find the mean value
g = np.random.random(30)
print(g)
gmean = g.mean()
print(gmean)

[0.0694111  0.40530445 0.08532043 0.34058247 0.90731412 0.32743492
 0.55866563 0.02714677 0.27145004 0.66440317 0.72208398 0.5086113
 0.45097606 0.53656557 0.18189378 0.34407573 0.47172893 0.08895707
 0.86784486 0.58804794 0.87436692 0.78630885 0.9219099  0.8926491
 0.06766909 0.27058212 0.47715557 0.25089482 0.74198324 0.8360077 ]
0.48457818728925056


In [15]:
# Create a 2d array with 1 on the border and 0 inside
h = np.ones((5,5))
h[1:-1, 1:-1] = 0
print(h)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# How to add a border (filled with 0's) around an existing array
i = np.random.permutation(25).reshape(5,5)
print("Original array: ")
print(i)

Original array: 
[[ 7  1 18 16  6]
 [12 22  8 14  9]
 [20  4 11  3 21]
 [ 0 24 19 15  5]
 [23  2 17 13 10]]


In [17]:
inew = np.pad(i, pad_width = 1, mode = 'constant', constant_values = 0)
print(inew)

[[ 0  0  0  0  0  0  0]
 [ 0  7  1 18 16  6  0]
 [ 0 12 22  8 14  9  0]
 [ 0 20  4 11  3 21  0]
 [ 0  0 24 19 15  5  0]
 [ 0 23  2 17 13 10  0]
 [ 0  0  0  0  0  0  0]]


In [18]:
# What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
j = np.diag(1+np.arange(4), k = -1)
print(j)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
k = np.zeros((8,8), dtype = int)
k[1::2, ::2] = 1
k[::2, 1::2] = 1
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [22]:
# Create a checkerboard 8x8 matrix using the tile function
l = np.tile(np.array([[1, 0], [0, 1]]), (4, 4))
print(l)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [23]:
# Normalize a 5x5 random matrix
m = np.random.random((5, 5))
mnorm = (m - np.mean(m)) / (np.std(m))
print(mnorm)

[[-1.75505353  0.77199581  0.40717708  1.44705532 -0.53728035]
 [-1.56958703  0.74906593  0.03282415 -0.67405815 -1.64450204]
 [ 1.04439265 -0.46901445  0.59641298 -1.13493138  1.26238921]
 [ 0.85138674 -1.86308759  0.88944979  0.90252908  0.27751877]
 [ 0.32315426  0.71521803  0.4794907  -1.1472548   0.04470883]]


In [24]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [25]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
n = np.dot(np.ones((5,3)), np.ones((3,2)))
print(n)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [26]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.
o = np.arange(15)
print(o)

o[(3 < o) & (o < 8)] *= -1
print(o)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14]


In [27]:
# What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [28]:
# Consider an integer vector Z, which of these expressions are legal?
o = np.arange(15)
o**o
2 << o >> 2
o <- o
1j*o
o/1/1
# o<o>o    Only this is invalid

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [29]:
# What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-2.14748365e+09])

In [30]:
# How to round away from zero a float array ?
p = np.random.uniform(-10, +10, 10)
pnew = np.copysign(np.ceil(np.abs(p)), p)
print(pnew)

[ 8.  6. -8.  3.  9.  7.  7.  1.  5. -9.]


In [31]:
# How to find common values between two arrays?
q1 = np.random.randint(0, 10, 10)
q2 = np.random.randint(0, 10, 10)
common = np.intersect1d(q1, q2)
print(common)

[2 4 8 9]


In [32]:
# How to ignore all numpy warnings (not recommended)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


In [33]:
# Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [34]:
# How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday", yesterday)
print("Today", today)
print("Tomorrow", tomorrow)

Yesterday 2021-07-10
Today 2021-07-11
Tomorrow 2021-07-12


In [35]:
# How to get all the dates corresponding to the month of July 2016
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [36]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [37]:
#  Extract the integer part of a random array of positive numbers using 4 different methods
r = np.random.uniform(0, 10, 10)

print(r - r%1)
print(r // 1)
print(np.floor(r))
print(r.astype(int))
print(np.trunc(r))

[0. 3. 6. 4. 9. 3. 1. 1. 3. 3.]
[0. 3. 6. 4. 9. 3. 1. 1. 3. 3.]
[0. 3. 6. 4. 9. 3. 1. 1. 3. 3.]
[0 3 6 4 9 3 1 1 3 3]
[0. 3. 6. 4. 9. 3. 1. 1. 3. 3.]


In [38]:
# Create a 5x5 matrix with row values ranging from 0 to 4
s = np.zeros((5,5))
s += np.arange(5)
print(s)

# without broadcasting
s = np.tile(np.arange(0, 5), (5,1))
print(s)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [39]:
# Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
t = np.fromiter(generate(),dtype=float,count=-1)
print(t)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [40]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
u = np.linspace(0,1,11,endpoint=False)[1:]
print(u)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [41]:
# Create a random vector of size 10 and sort it
v = np.random.random(10)
v.sort()
print(v)

[0.2367687  0.44911862 0.46575602 0.55239196 0.60781789 0.7169603
 0.91227116 0.9514157  0.9732926  0.98203959]


In [42]:
# How to sum a small array faster than np.sum
w = np.arange(10)
wsum = np.add.reduce(w)
print(wsum)

45


In [43]:
# Consider two random array A and B, check if they are equal
x1 = np.random.randint(0, 2, 5)
x2 = np.random.randint(0, 2, 5)
equal = np.allclose(x1, x2)
print(equal)

False


In [44]:
# Make an array immutable (read-only)
y = np.zeros(10)
y.flags.writeable = False
y[0] = 1

ValueError: assignment destination is read-only

In [45]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
z = np.random.random((10, 2))
z1, z2 = z[:, 0], z[:, 1]
z3 = np.sqrt(z1**2 + z2**2)
z4 = np.arctan2(z2, z1)
print(z2)
print(z1)

[0.9421211  0.87471636 0.19197229 0.81958512 0.20635735 0.84992399
 0.96964211 0.29450278 0.31463699 0.99494327]
[0.54376701 0.85608234 0.28304654 0.4128673  0.00598722 0.70323404
 0.41251047 0.36676493 0.41694451 0.72313856]


In [46]:
# Create random vector of size 10 and replace the maximum value by 0
aa = np.random.random(10)
aa[aa.argmax()] = 0
print(aa)

[5.94564423e-04 5.64637199e-01 3.48907987e-01 0.00000000e+00
 7.92961460e-01 3.39873764e-01 3.91245307e-02 8.33488035e-01
 3.28564338e-01 4.62143934e-01]


In [47]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
bb = np.zeros((10,10), [('x',float),('y',float)])
bb['x'], bb['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(bb)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

In [48]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
cc = np.arange(8)
dd = cc + 0.5
C = 1.0 / np.subtract.outer(cc, dd)
print(np.linalg.det(C))

3638.1636371179666


In [49]:
# Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [51]:
# How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
dd = np.zeros((25,25))
print(dd)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [52]:
# How to find the closest value (to a given scalar) in a vector?
ee = np.arange(100)
ef = np.random.uniform(0,100)
index = (np.abs(ee-ef)).argmin()
print(ee[index])

75


In [53]:
# Create a structured array representing a position (x,y) and a color (r,g,b)
ff = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(ff)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\mi\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [56]:
# Consider a random vector with shape (100,2) representing coordinates, find point by point distances
gg = np.random.random((10,2))
X,Y = np.atleast_2d(gg[:,0], gg[:,1])
gh = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(gh)

[[0.         0.74458716 0.19835759 0.38031731 0.19589957 0.58162241
  0.46570234 0.76334049 0.85949649 0.1364771 ]
 [0.74458716 0.         0.72645498 0.36878572 0.75845962 0.39804197
  0.67171109 0.38802979 0.97089486 0.61392618]
 [0.19835759 0.72645498 0.         0.40784837 0.39024676 0.46327256
  0.27823894 0.64548558 0.66148721 0.18016662]
 [0.38031731 0.36878572 0.40784837 0.         0.39756797 0.36798252
  0.4826034  0.50746605 0.87936051 0.25809287]
 [0.19589957 0.75845962 0.39024676 0.39756797 0.         0.69692764
  0.64169134 0.86821105 1.04635703 0.26056597]
 [0.58162241 0.39804197 0.46327256 0.36798252 0.69692764 0.
  0.29714662 0.18358188 0.57868302 0.45272414]
 [0.46570234 0.67171109 0.27823894 0.4826034  0.64169134 0.29714662
  0.         0.44880362 0.41401459 0.38642593]
 [0.76334049 0.38802979 0.64548558 0.50746605 0.86821105 0.18358188
  0.44880362 0.         0.61853036 0.63220147]
 [0.85949649 0.97089486 0.66148721 0.87936051 1.04635703 0.57868302
  0.41401459 0.61853

In [58]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?
hh = (np.random.rand(10)*100).astype(np.float32)
hi = hh.view(np.int32)
hi[:] = hh
print(hi)

[85 81  0 90 43  3  4 24 42 64]


In [59]:
# How to read the following file?
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [60]:
#  What is the equivalent of enumerate for numpy arrays?
ii = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) -1
(1, 2) -1
(1, 3) 7
(1, 4) 8
(2, 0) -1
(2, 1) -1
(2, 2) 9
(2, 3) 10
(2, 4) 11


In [61]:
# Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [62]:
# How to randomly place p elements in a 2D array?
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [63]:
# Subtract the mean of each row of a matrix
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.13773397  0.27645094 -0.24441454  0.34888987  0.38846071  0.34446157
  -0.45534077  0.05648445 -0.10945668 -0.46780158]
 [ 0.12797654  0.16006439  0.1630619  -0.52693996  0.00420071 -0.05314719
   0.29050844 -0.61655796  0.27197493  0.17885821]
 [ 0.43180851  0.1153563   0.12275371  0.12472817 -0.37377755 -0.22321254
  -0.1801247  -0.14974276  0.16024892 -0.02803806]
 [-0.3276671   0.15706656  0.21641988 -0.47092132  0.268166    0.02798302
  -0.31038752 -0.14069258  0.29494396  0.2850891 ]
 [ 0.22855823  0.43394753 -0.48172524 -0.24851147 -0.35640991  0.21889069
   0.23761766  0.20604936 -0.00943801 -0.22897885]]


In [64]:
# How to sort an array by the nth column?
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 1 4]
 [5 5 9]
 [5 3 8]]
[[6 1 4]
 [5 3 8]
 [5 5 9]]


In [65]:
# How to tell if a given 2D array has null columns?
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [66]:
# Find the nearest value from a given value in an array
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5056690731893536


In [67]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [69]:
# Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [70]:
# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 3. 5. 3. 5. 2. 1. 4. 3.]


In [72]:
# How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [73]:
# Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [74]:
# Considering a four dimensions array, how to get sum over the last two axis at once? 
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 64 69 56]
 [74 59 44 56]
 [63 62 51 60]]


In [75]:
# Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.57331277 0.60823323 0.529859   0.48947711 0.60190002 0.55062868
 0.51197804 0.48524258 0.52657898 0.70602471]


In [76]:
# How to get the diagonal of a dot product?
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
np.einsum("ij,ji->i", A, B)

array([40, 73, 52])

In [77]:
# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
