In [82]:
import numpy as np

In [83]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [84]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a.ndim

2

In [87]:
a.size

9

In [88]:
a.shape

(3, 3)

In [89]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [90]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [92]:
np.linspace(1, 10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [93]:
a.min()

1

In [14]:
a.max()

9

In [15]:
a.sum()

45

In [16]:
a.sum(axis = 0)

array([12, 15, 18])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a.sum(axis = 1)     

array([ 6, 15, 24])

In [19]:
x = np.array([[1,2], [2,4]])
y = np.array([[3,4], [2,5]])

In [20]:
x+y

array([[4, 6],
       [4, 9]])

In [21]:
x-y

array([[-2, -2],
       [ 0, -1]])

In [22]:
x*y

array([[ 3,  8],
       [ 4, 20]])

In [23]:
x/y

array([[0.33333333, 0.5       ],
       [1.        , 0.8       ]])

In [24]:
x.dot(y)     #matrix  multiplication

array([[ 7, 14],
       [14, 28]])

In [25]:
s = np.array([1,2,3,4,5])

In [27]:
s[0:2]    #slices from index 0 to 2-1

array([1, 2])

In [28]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a[2,1]

8

In [33]:
a[0:2, 1]      # from 0 to 2-1 row it will print index 1

array([2, 5])

In [34]:
a[-1]     # means the last row

array([7, 8, 9])

In [36]:
a[-1, 1:3]

array([8, 9])

In [37]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [39]:
for column in a:
    print(column)

[1 2 3]
[4 5 6]
[7 8 9]


In [41]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [43]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [44]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
np.vstack((a,b))        # puts array a on the head of array b (vertical stacking)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [47]:
np.hstack((a,b))        # puts array a beside array b (horizontal stacking)

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [49]:
a = np.arange(30).reshape(2,15)

In [50]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
np.hsplit(a,3)        #splits array a into 3 equal arrays

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [52]:
a = np.arange(12).reshape(3,4)

In [53]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
b = a > 5

In [55]:
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
a[b]

array([ 6,  7,  8,  9, 10, 11])

In [59]:
a[b] = -1

In [60]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

In [61]:
a = np.arange(12).reshape(3,4)

In [62]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [65]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [66]:
for cell in a.flatten():          #same as previous process
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [67]:
for x in np.nditer(a, order='C'):     # it goes by row after row
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [69]:
for x in np.nditer(a, order='F'):      # it goes by column after column which is called fortran order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [70]:
for x in np.nditer(a, order='F', flags=['external_loop']):      # it goes by column after column and prints column
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [75]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x*x

In [76]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [73]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [78]:
arr = np.array(42)
print(arr)
arr.ndim

42


0

In [80]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
arr.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [81]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
