In [1]:
# Import the numpy package under the name np
import numpy as np

In [3]:
# Print the numpy version and the configuration
print(np.__version__)

1.18.1


In [5]:
# Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# How to find the memory size of any array
print(x.size)

10


In [8]:
# How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [10]:
# Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49
z = np.arange(10, 49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
# Reverse a vector (first element becomes last) 
rz = z[::-1]
print(rz)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
# Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
b = np.array([1,2,0,0,4,0])
print(b)

c = np.nonzero(b)
print("Indices of non-zero elements: ", c)

[1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [15]:
# Create a 3x3 identity matrix
d = np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Create a 3x3x3 array with random values
e = np.random.random((3, 3, 3))
print(e)

[[[0.56702921 0.53466934 0.47991633]
  [0.75167525 0.68810874 0.24379958]
  [0.0617454  0.34818391 0.6615023 ]]

 [[0.80569385 0.81377731 0.3056111 ]
  [0.34480583 0.96718969 0.7533942 ]
  [0.84088958 0.80372914 0.38876636]]

 [[0.1572346  0.58073066 0.45537922]
  [0.48584654 0.15282168 0.234871  ]
  [0.11995312 0.38842688 0.35108722]]]


In [17]:
# Create a 10x10 array with random values and find the minimum and maximum values
f = np.random.random((10, 10))
print(f)
fmin = f.min()
fmax = f.max()
print(fmin, fmax)

[[0.47917009 0.14518738 0.49587371 0.65574467 0.33774721 0.56952153
  0.84921999 0.96994809 0.72754524 0.58959477]
 [0.66422173 0.08628981 0.81915911 0.11660944 0.16486224 0.81766277
  0.49521314 0.27400292 0.82109487 0.93492948]
 [0.04891651 0.88448044 0.32157399 0.15030475 0.67330227 0.18595451
  0.44709822 0.66215612 0.20266301 0.33745586]
 [0.15865491 0.6447967  0.54308586 0.49871387 0.05410564 0.39865648
  0.93407631 0.79730672 0.12802781 0.29839029]
 [0.16521322 0.11146474 0.049224   0.23520107 0.64729443 0.98293347
  0.56065133 0.1727568  0.70321518 0.54086604]
 [0.1136598  0.71659787 0.32290835 0.86578248 0.45832571 0.23432678
  0.09064789 0.02371393 0.77306111 0.06195216]
 [0.34888676 0.68879928 0.19172263 0.55636209 0.76468302 0.52083635
  0.94439676 0.05165169 0.85366404 0.31542979]
 [0.76855702 0.18661439 0.19101499 0.15797998 0.55736318 0.75125866
  0.45295773 0.54968534 0.85559451 0.47150036]
 [0.5352739  0.72017144 0.38678483 0.80374553 0.84880456 0.00632135
  0.02208447

In [18]:
# Create a random vector of size 30 and find the mean value
g = np.random.random(30)
print(g)
gmean = g.mean()
print(gmean)

[0.94880092 0.8902632  0.5658135  0.11944983 0.38177263 0.68489182
 0.91892836 0.88668307 0.10608477 0.50323794 0.80193749 0.58938916
 0.80291172 0.30051851 0.20955927 0.00597843 0.88549064 0.01697789
 0.77385767 0.09302881 0.16031679 0.49142155 0.83121072 0.74424183
 0.82440636 0.13279145 0.88935931 0.52211514 0.1215271  0.13784072]
0.5113602208678222


In [23]:
# Create a 2d array with 1 on the border and 0 inside
h = np.ones((5,5))
h[1:-1, 1:-1] = 0
print(h)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
