In [1]:
# Import the numpy package under the name np
import numpy as np

In [3]:
# Print the numpy version and the configuration
print(np.__version__)

1.18.1


In [5]:
# Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# How to find the memory size of any array
print(x.size)

10


In [8]:
# How to get the documentation of the numpy add function from the command line?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [10]:
# Create a null vector of size 10 but the fifth value which is 1
y = np.zeros(10)
y[4] = 1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
# Create a vector with values ranging from 10 to 49
z = np.arange(10, 49)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
# Reverse a vector (first element becomes last) 
rz = z[::-1]
print(rz)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
# Create a 3x3 matrix with values ranging from 0 to 8
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
b = np.array([1,2,0,0,4,0])
print(b)

c = np.nonzero(b)
print("Indices of non-zero elements: ", c)

[1 2 0 0 4 0]
Indices of non-zero elements:  (array([0, 1, 4], dtype=int64),)


In [15]:
# Create a 3x3 identity matrix
d = np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Create a 3x3x3 array with random values
e = np.random.random((3, 3, 3))
print(e)

[[[0.56702921 0.53466934 0.47991633]
  [0.75167525 0.68810874 0.24379958]
  [0.0617454  0.34818391 0.6615023 ]]

 [[0.80569385 0.81377731 0.3056111 ]
  [0.34480583 0.96718969 0.7533942 ]
  [0.84088958 0.80372914 0.38876636]]

 [[0.1572346  0.58073066 0.45537922]
  [0.48584654 0.15282168 0.234871  ]
  [0.11995312 0.38842688 0.35108722]]]
